# Scrapy settings for missilery_scraper project

from .constants import (
    BOT_NAME, SPIDER_MODULES, NEWSPIDER_MODULE, ROBOTSTXT_OBEY,
    DOWNLOAD_DELAY, RANDOMIZE_DOWNLOAD_DELAY, CONCURRENT_REQUESTS,
    CONCURRENT_REQUESTS_PER_DOMAIN, USER_AGENT, ITEM_PIPELINES,
    LOG_LEVEL, RETRY_TIMES, RETRY_HTTP_CODES, DOWNLOAD_TIMEOUT,
    COOKIES_ENABLED, DEFAULT_REQUEST_HEADERS
)

# Bot configuration
BOT_NAME = BOT_NAME
SPIDER_MODULES = SPIDER_MODULES
NEWSPIDER_MODULE = NEWSPIDER_MODULE

# Obey robots.txt rules
ROBOTSTXT_OBEY = ROBOTSTXT_OBEY

# Configure delays for requests for the same website (default: 0)
DOWNLOAD_DELAY = DOWNLOAD_DELAY
RANDOMIZE_DOWNLOAD_DELAY = RANDOMIZE_DOWNLOAD_DELAY

# Configure concurrent requests
CONCURRENT_REQUESTS = CONCURRENT_REQUESTS
CONCURRENT_REQUESTS_PER_DOMAIN = CONCURRENT_REQUESTS_PER_DOMAIN

# Configure user agent
USER_AGENT = USER_AGENT

# Configure pipelines
ITEM_PIPELINES = ITEM_PIPELINES

# Configure logging
LOG_LEVEL = LOG_LEVEL

# Configure retry settings
RETRY_TIMES = RETRY_TIMES
RETRY_HTTP_CODES = RETRY_HTTP_CODES

# Configure download timeout
DOWNLOAD_TIMEOUT = DOWNLOAD_TIMEOUT

# Configure cookies
COOKIES_ENABLED = COOKIES_ENABLED

# Configure headers
DEFAULT_REQUEST_HEADERS = DEFAULT_REQUEST_HEADERS
